### ISSUE TITLE
Android inplementation

### ISSUE THREAD

**Issue by sacheen** [markneh/react-native-esim#5]
Hello!

I was wondering if you ever implemented the Android portion of setting up the E-Sim.
Both Apple and Androids documentation are not very clear on how to set this up.
I have applied for an entitlement for iOS, still waiting on that.

Do we need anything to be-able to open the LPA  on android?
I tried doing this: https://medium.com/@kishanvaghela/activate-esim-using-ipa-7d7c133759f5

but doesn't seem to work.

If you have had any success with Android, would you mind sharing your implementation.

Thank you.

**Comment by markneh** [comment]
@sacheen 

Hi. Well, I haven't done the Android part yet, but you can check out these forks:

https://github.com/tyler-whitman/react-native-esim
https://github.com/FrLallemandArhs/react-native-esim

However, I've never tried them, so I'm not sure if they work.

As for API access, you actually need an eSIM entitlement in order to use it. Pretty much the same thing (but a bit more complicated) is required for Android.

**Comment by sacheen** [comment]
@markneh thanks! i'll have a look at those forks, appreciate your feedback.
Is the Android entitlement part the signing of the packages? or is it something different?

**Comment by markneh** [comment]
@sacheen I'm not totally sure, but your eSIM profile should at least indicate your app applicationId. I might be wrong on this, though.

**Comment by sacheen** [comment]
No worries, I see you need to supply the SM-DP+ / Operator with the sha1 / sha2 signature and your application id, they setup the meta data that comes down to enable access to the EuiccManager. 
if it doesn't match then method calls to the EuiccManager will fail. 

I've included a link to it if you interested.

https://source.android.com/docs/core/connect/esim-overview#carrier-privileges

**Comment by aleena-adnan1** [comment]
did you succeeded in achieving this @sacheen ?

**Comment by sacheen** [comment]
@aleena-adnan1 haven't tried anything as yet. We still waiting on the parent network to setup the E-Sims, until then we cannot do much.
